node{
stage('SCM Checkout'){
git 'https://github.com/karthiktr147/deploymentwar.git'
}
stage('Compile Package')
{
def mvnHome= tool name : 'Maven 3', type : 'maven'
sh "${mvnHome}/bin/mvn package
}
}
